name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install fastapi uvicorn
      - run: uvicorn api.server:app --host 0.0.0.0 --port 8000 & sleep 5 && kill $!
